services:
 db:
   image: postgres:16
   container_name: movie_db
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: movie_db
   ports:
     - "5432:5432"
   volumes:
     - movie_db_data:/var/lib/postgresql/data


volumes:
 movie_db_data:
